// Copyright (c) The Vignette Authors
// Licensed under MIT. See LICENSE for details.

namespace Sekai.Framework.IO.HID;

/// <summary>
/// This represents one Silk.NET Keyboard/Mouse/Joystick Button ID.
/// Note that this does not handle mouse and joystick pointers and
/// only specifically the buttons.
///<br></br>
/// This is handled at <see cref="InputSystem"/>
/// </summary>
// TODO: Get all Silk.NET button IDs and have the input manager match that.
public enum KeyName
{
    #region Common
    // Common ID for all unknown input types.
    Unknown = -1,
    None = 0,
    #endregion
    #region Keyboard
    Tab,
    Enter,
    Space,
    Backspace,
    UpArrow,
    DownArrow,
    LeftArrow,
    RightArrow,
    // You may notice we register keys with left and right versions as one key
    // This is intentional by design. As much as possible we treat
    // them as one key so they have one common behavior.
    Alt,
    Ctrl,
    Shift,
    // This is a bad idea to give access to the super key
    // But I know someone would want Super locking, so we'll add it.
    Super,
    Command,
    CapsLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Ins,
    Del,
    PgDn,
    PgUp,
    Home,
    End,
    Pause,
    Semicolon,
    #endregion
    #region Keypad
    // We're going to replicate Source Engine's bind IDs here
    KpHome,
    KpUpArrow,
    KpDownArrow,
    KpLeftArrow,
    KpRightArrow,
    KpIns,
    KpEnter,
    KpDel,
    KpSlash,
    KpMinus,
    KpPlus,
    KpMultiply,
    KpEquals,
    Kp5,
    KpEnd,
    #endregion
    #region Joystick
    // Auto-generated by Intellicode.
    // God I love AI-assisted programming.
    Joy1,
    Joy2,
    Joy3,
    Joy4,
    Joy5,
    Joy6,
    Joy7,
    Joy8,
    Joy9,
    Joy10,
    Joy11,
    Joy12,
    Joy13,
    Joy14,
    Joy15,
    Joy16,
    Joy17,
    Joy18,
    Joy19,
    Joy20,
    Joy21,
    Joy22,
    Joy23,
    Joy24,
    Joy25,
    Joy26,
    Joy27,
    Joy28,
    Joy29,
    Joy30,
    Joy31,
    Joy32,
    #endregion
    #region Mouse
    Mouse1,
    Mouse2,
    Mouse3,
    Mouse4,
    Mouse5,
    MouseWheelUp,
    MouseWheelDown,
    #endregion
}
