name: Publish
on:
 release:
     types: [ prereleased, released ]

jobs:
  publish:
    runs-on: windows-latest
    environment: ${{ github.event.release.prerelease && 'Staging' || 'Production' }}
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Pack
        run: |
          dotnet pack --include-symbols -o release source/Sekai
          dotnet pack --include-symbols -o release source/Sekai.Null
          dotnet pack --include-symbols -o release source/Sekai.OpenAL
          dotnet pack --include-symbols -o release source/Sekai.OpenGL
          dotnet pack --include-symbols -o release source/Sekai.SDL
          dotnet pack --include-symbols -o release source/Sekai.Skia
          dotnet pack --include-symbols -o release source/Sekai.Windows
          dotnet pack --include-symbols -o release source/Sekai.Xunit

      - name: Publish packages
        run: dotnet nuget push ${{ github.workspace }}\release\*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ vars.NUGET_SRC }}
