name: Report
on:
  workflow_run:
    workflows: [ 'Test' ]
    types:
      - completed

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    steps:
      - name: Report Tests
        uses: dorny/test-reporter@v1.4.2
        with:
          artifact: results-(.*)
          name: Test Report on $1
          path: '*.trx'
          reporter: dotnet-trx

      - name: Download Artifact
        uses: actions/download-artifact@v3

      - name: Extract Artifact
        run: unzip $(ls | grep "^results-" -m 1) -d results

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./results/coverage.info